# Site settings
title: NÃ¤hzwockel
email: bestellen@naehzwockel.de
url: "https://naehzwockel.de"
author: NÃ¤hzwockel
tagline: "Wiederverwendbare Produkte mit Liebe handgemacht"
description: "â™»ï¸ Wiederverwendbare Produkte ğŸŒ MÃ¼ll vermeiden ğŸƒ Umwelt schonen ğŸ’• Mit Liebe handgemacht ğŸ“¦ Verkauf von Masken, BrottÃ¼ten, GemÃ¼sebeuteln, Bestecktaschen, WÃ¤rmekissen uvm."
logo: "/img/logo.png"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#FFFFFF'
  links: '#219ab3'

# Footer settings
footer: NÃ¤hzwockel

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
sociallinks:
  - title: instagram
    url: https://instagram.com/naehzwockel

social:
  name: NÃ¤hzwockel
  links:
    - https://instagram.com/naehzwockel

lang: de_DE

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag

image:
  path: "/img/logo.png"
  height: 1200
  width: 1200

seo:
  name: "NÃ¤hzwockel"
  type: LocalBusiness
  links:
    - https://instagram.com/naehzwockel
